### ISSUE TITLE
myvd.conf results in no identity providers

### ISSUE THREAD

**Issue by ram4ibm** [OpenUnison/openunison-k8s-login-activedirectory#13]
[2018-11-13 13:36:00,001][local_Worker-2] INFO  JobRunShell - Job admin.clearSessions threw a JobExecutionException:
org.quartz.JobExecutionException: com.tremolosecurity.provisioning.core.ProvisioningException: No identity providers
        at com.tremolosecurity.provisioning.scheduler.UnisonJob.execute(UnisonJob.java:59) ~[unison-sdk-1.0.16.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [quartz-2.3.0.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.3.0.jar:?]
Caused by: com.tremolosecurity.provisioning.core.ProvisioningException: No identity providers
        at com.tremolosecurity.idp.providers.oidc.model.jobs.ClearSessions.execute(ClearSessions.java:35) ~[unison-idp-openidconnect-1.0.16.jar:?]
        at com.tremolosecurity.provisioning.scheduler.UnisonJob.execute(UnisonJob.java:57) ~[unison-sdk-1.0.16.jar:?]
        ... 2 more
[2018-11-13 13:36:52,568][Thread-19] WARN  SessionManagerImpl - Clearing 0 sessions
[2018-11-13 13:37:00,001][local_Worker-3] INFO  JobRunShell - Job admin.clearSessions threw a JobExecutionException:
org.quartz.JobExecutionException: com.tremolosecurity.provisioning.core.ProvisioningException: No identity providers
        at com.tremolosecurity.provisioning.scheduler.UnisonJob.execute(UnisonJob.java:59) ~[unison-sdk-1.0.16.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [quartz-2.3.0.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.3.0.jar:?]
Caused by: com.tremolosecurity.provisioning.core.ProvisioningException: No identity providers

Followed the instruction as per the documentation, I am using openldap for the authentication. Testing the configuration at the moment. Even used admin to get the connection established. But didnt work

Openldap is hosted inside the same K8s cluster. Receiving handshake from LB to the openldap. Hence TLS may not be an issue.

However, openunison is reporting it as no identity provider

**Comment by mlbiam** [comment]
@ram4ibm does this error continue or does it happen just in the very beginning?  I should change this to a warning instead of an error.  Its because the oidc session job clearer was initialized after the identity provider was initialized.  If it doesn't continuously get printed in the logs it can be ignored.

When you login, there should be logs that show the ldap flow.  Look for `DumpTransaction` in the pod logs.  It should show you the ldap requests and responses.
