### ISSUE TITLE
First login problem with NullPointerException: null

### ISSUE THREAD

**Issue by 3d-pro** [OpenUnison/openunison-k8s-login-activedirectory#35]
Hi, i just deployed OpenUnison on Kops cluster. After the first login, it shown "Login Choice Reset" page. Then for 2nd login, it shown error page with the pod throwing this error. 
```
[2019-06-11 11:02:44,083][XNIO-1 task-4] INFO  AccessLog - SRCH op=2 con=1 base='o=Data' filter='(uid=usera)' scope='2' attribs=''
[2019-06-11 11:02:44,120][XNIO-1 task-4] INFO  AccessLog - RESULT op=2 con=1 result=0 time=38
[2019-06-11 11:02:44,149][XNIO-1 task-4] INFO  AccessLog - BIND op=3 con=2 dn='CN=User A,OU=Devops,OU=Development,OU=Peoples,ou=activedirectory,o=Data'
[2019-06-11 11:02:44,180][XNIO-1 task-4] INFO  AccessLog - RESULT op=3 con=2 result=0 time=31
[2019-06-11 11:02:44,451][XNIO-1 task-4] INFO  AccessLog - [Error] - scale - https://k8s.xxx.com/auth/formLogin - uid=Anonymous,o=Tremolo - NONE [100.119.160.0] - [fa8272940ba3ea2c4dd55a92f059bd53ceee81be3]
[2019-06-11 11:02:44,451][XNIO-1 task-4] ERROR ConfigSys - Could not process request
java.lang.NullPointerException: null
	at com.tremolosecurity.provisioning.providers.K8sCrdUserProvider.createUser(K8sCrdUserProvider.java:95) ~[unison-applications-k8s-1.0.16.jar:?]
	at com.tremolosecurity.provisioning.providers.K8sCrdUserProvider.syncUser(K8sCrdUserProvider.java:191) ~[unison-applications-k8s-1.0.16.jar:?]
	at com.tremolosecurity.provisioning.core.ProvisioningTargetImpl.syncUser(ProvisioningTargetImpl.java:107) ~[unison-server-core-1.0.16.jar:?]
	at com.tremolosecurity.provisioning.tasks.Provision.doTask(Provision.java:112) ~[unison-server-core-1.0.16.jar:?]
	at com.tremolosecurity.provisioning.core.WorkflowTaskImpl.runSubTasks(WorkflowTaskImpl.java:165) ~[unison-server-core-1.0.16.jar:?]
	at com.tremolosecurity.provisioning.tasks.Mapping.doTask(Mapping.java:67) ~[unison-server-core-1.0.16.jar:?]
	at com.tremolosecurity.provisioning.core.WorkflowImpl.executeWorkflow(WorkflowImpl.java:254) ~[unison-server-core-1.0.16.jar:?]
	at com.tremolosecurity.provisioning.core.WorkflowImpl.executeWorkflow(WorkflowImpl.java:148) ~[unison-server-core-1.0.16.jar:?]
	at com.tremolosecurity.provisioning.core.WorkflowImpl.executeWorkflow(WorkflowImpl.java:541) ~[unison-server-core-1.0.16.jar:?]
	at com.tremolosecurity.provisioning.auth.JITAuthMech.doGet(JITAuthMech.java:126) ~[unison-server-core-1.0.16.jar:?]
	at com.tremolosecurity.provisioning.auth.JITAuthMech.doPost(JITAuthMech.java:75) ~[unison-server-core-1.0.16.jar:?]
	at com.tremolosecurity.proxy.auth.sys.AuthManagerImpl.execAuth(AuthManagerImpl.java:412) ~[unison-server-core-1.0.16.jar:?]
	at com.tremolosecurity.proxy.auth.sys.AuthManagerImpl.nextAuth(AuthManagerImpl.java:125) ~[unison-server-core-1.0.16.jar:?]
	at com.tremolosecurity.proxy.auth.sys.AuthManagerImpl.nextAuth(AuthManagerImpl.java:83) ~[unison-server-core-1.0.16.jar:?]
	at com.tremolosecurity.proxy.auth.FormLoginAuthMech.doPost(FormLoginAuthMech.java:217) ~[unison-server-core-1.0.16.jar:?]
	at com.tremolosecurity.proxy.auth.AuthMgrSys.doAuthMgr(AuthMgrSys.java:190) ~[unison-server-core-1.0.16.jar:?]
	at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:126) ~[unison-server-core-1.0.16.jar:?]
	at com.tremolosecurity.proxy.auth.AzSys.doAz(AzSys.java:89) ~[unison-sdk-1.0.16.jar:?]
	at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:111) ~[unison-server-core-1.0.16.jar:?]
	at com.tremolosecurity.proxy.auth.AuthSys.doAuth(AuthSys.java:118) ~[unison-server-core-1.0.16.jar:?]
	at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:105) ~[unison-server-core-1.0.16.jar:?]
	at com.tremolosecurity.proxy.ConfigSys.doConfig(ConfigSys.java:293) [unison-server-core-1.0.16.jar:?]
	at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:93) [unison-server-core-1.0.16.jar:?]
	at com.tremolosecurity.filter.UnisonServletFilter.doFilter(UnisonServletFilter.java:290) [unison-server-core-1.0.16.jar:?]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-2.0.19.Final.jar:2.0.19.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-2.0.19.Final.jar:2.0.19.Final]
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) [undertow-servlet-2.0.19.Final.jar:2.0.19.Final]
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) [undertow-servlet-2.0.19.Final.jar:2.0.19.Final]
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) [undertow-servlet-2.0.19.Final.jar:2.0.19.Final]
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) [undertow-servlet-2.0.19.Final.jar:2.0.19.Final]
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132) [undertow-servlet-2.0.19.Final.jar:2.0.19.Final]
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) [undertow-servlet-2.0.19.Final.jar:2.0.19.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.0.19.Final.jar:2.0.19.Final]
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) [undertow-core-2.0.19.Final.jar:2.0.19.Final]
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) [undertow-servlet-2.0.19.Final.jar:2.0.19.Final]
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) [undertow-core-2.0.19.Final.jar:2.0.19.Final]
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) [undertow-servlet-2.0.19.Final.jar:2.0.19.Final]
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) [undertow-core-2.0.19.Final.jar:2.0.19.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.0.19.Final.jar:2.0.19.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.0.19.Final.jar:2.0.19.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292) [undertow-servlet-2.0.19.Final.jar:2.0.19.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81) [undertow-servlet-2.0.19.Final.jar:2.0.19.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138) [undertow-servlet-2.0.19.Final.jar:2.0.19.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135) [undertow-servlet-2.0.19.Final.jar:2.0.19.Final]
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) [undertow-servlet-2.0.19.Final.jar:2.0.19.Final]
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) [undertow-servlet-2.0.19.Final.jar:2.0.19.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272) [undertow-servlet-2.0.19.Final.jar:2.0.19.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81) [undertow-servlet-2.0.19.Final.jar:2.0.19.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104) [undertow-servlet-2.0.19.Final.jar:2.0.19.Final]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:364) [undertow-core-2.0.19.Final.jar:2.0.19.Final]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830) [undertow-core-2.0.19.Final.jar:2.0.19.Final]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

The error is very vague. Hoping anyone here can guide me on how to debug it. thanks!

**Comment by mlbiam** [comment]
Does the user you re logging in with have a `sn` (last name) attribute?

**Comment by 3d-pro** [comment]
> Does the user you re logging in with have a `sn` (last name) attribute?

The test account does not and that's the root problem. thanks for the help!
