### ISSUE TITLE
Getting Java.lang.NullPointerException on initial logon.

### ISSUE THREAD

**Issue by christopherkrull** [OpenUnison/openunison-k8s-login-activedirectory#51]
After we the deployment on initial logon to the k8sou.k8s url we are getting a java.lang.nullpointerexception. Any thoughts as to where I should start looking as to why it is not able to look up the user?

[2019-10-10 16:37:58,703][XNIO-1 task-14] INFO  AccessLog - [Error] - scale - https://k8sou.k8s.****/auth/formLogin - uid=Anonymous,o=Tremolo - NONE [10.233.111.0] - [f19d084f5957c6f8bcd97e29b543a2e3bae0db0a0]
[2019-10-10 16:37:58,703][XNIO-1 task-14] ERROR ConfigSys - Could not process request
java.lang.NullPointerException: null
        at com.tremolosecurity.proxy.auth.FormLoginAuthMech.doPost(FormLoginAuthMech.java:151) ~[unison-server-core-1.0.17.jar:?]
        at com.tremolosecurity.proxy.auth.AuthMgrSys.doAuthMgr(AuthMgrSys.java:193) ~[unison-server-core-1.0.17.jar:?]
        at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:126) ~[unison-server-core-1.0.17.jar:?]
        at com.tremolosecurity.proxy.auth.AzSys.doAz(AzSys.java:89) ~[unison-sdk-1.0.17.jar:?]
        at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:111) ~[unison-server-core-1.0.17.jar:?]
        at com.tremolosecurity.proxy.auth.AuthSys.doAuth(AuthSys.java:118) ~[unison-server-core-1.0.17.jar:?]
        at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:105) ~[unison-server-core-1.0.17.jar:?]
        at com.tremolosecurity.proxy.ConfigSys.doConfig(ConfigSys.java:293) [unison-server-core-1.0.17.jar:?]
        at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:93) [unison-server-core-1.0.17.jar:?]
        at com.tremolosecurity.filter.UnisonServletFilter.doFilter(UnisonServletFilter.java:290) [unison-server-core-1.0.17.jar:?]
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-2.0.22.Final.jar:2.0.22.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-2.0.22.Final.jar:2.0.22.Final]
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) [undertow-servlet-2.0.22.Final.jar:2.0.22.Final]
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) [undertow-servlet-2.0.22.Final.jar:2.0.22.Final]
        at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) [undertow-servlet-2.0.22.Final.jar:2.0.22.Final]
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) [undertow-servlet-2.0.22.Final.jar:2.0.22.Final]
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132) [undertow-servlet-2.0.22.Final.jar:2.0.22.Final]
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) [undertow-servlet-2.0.22.Final.jar:2.0.22.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.0.22.Final.jar:2.0.22.Final]
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) [undertow-core-2.0.22.Final.jar:2.0.22.Final]
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) [undertow-servlet-2.0.22.Final.jar:2.0.22.Final]
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) [undertow-core-2.0.22.Final.jar:2.0.22.Final]
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) [undertow-servlet-2.0.22.Final.jar:2.0.22.Final]
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) [undertow-core-2.0.22.Final.jar:2.0.22.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.0.22.Final.jar:2.0.22.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.0.22.Final.jar:2.0.22.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292) [undertow-servlet-2.0.22.Final.jar:2.0.22.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81) [undertow-servlet-2.0.22.Final.jar:2.0.22.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138) [undertow-servlet-2.0.22.Final.jar:2.0.22.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135) [undertow-servlet-2.0.22.Final.jar:2.0.22.Final]
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) [undertow-servlet-2.0.22.Final.jar:2.0.22.Final]
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) [undertow-servlet-2.0.22.Final.jar:2.0.22.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272) [undertow-servlet-2.0.22.Final.jar:2.0.22.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81) [undertow-servlet-2.0.22.Final.jar:2.0.22.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104) [undertow-servlet-2.0.22.Final.jar:2.0.22.Final]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376) [undertow-core-2.0.22.Final.jar:2.0.22.Final]
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830) [undertow-core-2.0.22.Final.jar:2.0.22.Final]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

**Comment by mlbiam** [comment]
Was your `OU_HOST` set to the correct host name?  This usually happens when the host name in `OU_HOST` isn't the same as the hostname in your URL

**Comment by christopherkrull** [comment]
Not sure what it was, I do have the values set correctly. I removed openunison and then added back. Now I am a little bit further, having issues talking to AD over 636.

**Comment by mlbiam** [comment]
Is your ldaps certificate added to the `orchestra` CR as a trusted cert?

**Comment by christopherkrull** [comment]
i have the cacert and the actual ad server cert in the configmap directory. I am assuming those are enough?

**Comment by christopherkrull** [comment]
Current error

[2019-10-11 15:18:06,093][Thread-11] WARN  LDAPConnectionPool - Could not execute ldap heartbeat for ADServer.io/636, recreating connection
com.novell.ldap.LDAPException: No Such Object
        at com.novell.ldap.LDAPResponse.getResultException(LDAPResponse.java:407) ~[jldap-1.0.0.jar:?]
        at com.novell.ldap.LDAPResponse.chkResultCode(LDAPResponse.java:370) ~[jldap-1.0.0.jar:?]
        at com.novell.ldap.LDAPSearchResults.next(LDAPSearchResults.java:289) ~[jldap-1.0.0.jar:?]
        at net.sourceforge.myvd.inserts.ldap.LDAPConnectionPool.executeHeartBeat(LDAPConnectionPool.java:229) [myvd-server-1.0.6.jar:?]
        at net.sourceforge.myvd.inserts.ldap.LDAPHeartBeat.run(LDAPHeartBeat.java:43) [myvd-server-1.0.6.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

**Comment by mlbiam** [comment]
take a look at the `orchestra` cr (`kubectl edit openunison orchestra -n openunison` ) and look at `AD_BASE_DN`.  Its probably not correct.  Thats what we check to make sure the domain controller is healthy

**Comment by christopherkrull** [comment]
The base dn I have is the OU where users and groups who have access should live correct? or is it just the OU where the bind account lives?

**Comment by mlbiam** [comment]
you're correct.  but ti doesn't appear that base is correct.
