### ISSUE TITLE
AD_BIND_DN IllegalArgumentException:

### ISSUE THREAD

**Issue by TomerG711** [OpenUnison/openunison-k8s-login-activedirectory#53]
I'm looking at the logs of my `openunison-orchestra-*` pod (under `openunison` namespace, and it seems that whenever OpenUnison attempt to send heartbeat to the AD, it keep throwing:

        Exception in thread "Thread-11" java.lang.IllegalArgumentException: <my AD_BIND_DN value>

        at com.novell.ldap.util.DN.<init>(DN.java:440)

        at net.sourceforge.myvd.inserts.ldap.LDAPConnectionPool.executeHeartBeat(LDAPConnectionPool.java:224)

        at net.sourceforge.myvd.inserts.ldap.LDAPHeartBeat.run(LDAPHeartBeat.java:43)

        at java.lang.Thread.run(Thread.java:748)`

Now this happens both if I set AD_BIND_DN value to simple AD username, and if I'm using full DN (which is of the fromat: `CN=..,,OU=...,OU=,...OU=...,OU=...,OU=...,DC=...,DC=...,DC=...,DC=...`)
Why does it happen? How can it be fixed?

**Comment by mlbiam** [comment]
Without seeing the actual DN I can't tell you the problem but based on what you have i do see a `,,` after `CN=`, not sure if thats in your actual DN or not.
