### ISSUE TITLE
Can't find Kubectl during deployment

### ISSUE THREAD

**Issue by tkg61** [OpenUnison/openunison-k8s-login-activedirectory#60]
Hello, 

Working with a basic deployment of K8s using [Deepops](https://github.com/NVIDIA/deepops) and during the deployment process of openunison following the readme both containers being stood up run into the issue of:

`Processing - '/etc/extracerts/trusted-adldaps.pem'
Loading CertUtils
Creating openunison keystore
Runing kubectl create
Exception in thread "main" java.lang.RuntimeException: java.io.IOException: Cannot run program "kubectl": error=2, No such file or directory
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:397)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:150)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:249)
	at com.tremolosecurity.kubernetes.artifacts.run.RunDeployment.main(RunDeployment.java:123)
Caused by: java.io.IOException: Cannot run program "kubectl": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:621)
	at java.lang.Runtime.exec(Runtime.java:486)
	at com.tremolosecurity.kubernetes.artifacts.util.K8sUtils.kubectlCreate(K8sUtils.java:778)
	at jdk.nashorn.internal.scripts.Script$\^eval\_.:program(<eval>:46)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	... 6 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 13 more`

Deployed using this command: 

`curl https://raw.githubusercontent.com/TremoloSecurity/kubernetes-artifact-deployment/master/src/main/bash/deploy_openunison.sh | bash -s /opt/openunison/configmaps /opt/openunison/secrets https://raw.githubusercontent.com/OpenUnison/openunison-k8s-login-activedirectory/master/src/main/yaml/artifact-deployment.yaml`

input.props:

`

- OU_HOST=mylogin.example.org
- K8S_DASHBOARD_HOST=mydashboard.example.org
- K8S_URL=https://mymgr1.example.org:6443
- AD_BASE_DN=OU=General,OU=User,DC=example,DC=org
- AD_HOST=myad.example.org
- AD_PORT=636
- AD_BIND_DN=CN=MYKUBE-LOGIN-SVC-ACCT,OU=Service Accounts,OU=Users,DC=example,DC=org
- AD_CON_TYPE=ldaps
- SRV_DNS=false
- OU_CERT_OU=my-k8s-cluster
- OU_CERT_O=TestOrg
- OU_CERT_L=Alexandria
- OU_CERT_ST=Virgina
- OU_CERT_C=US
- USE_K8S_CM=true
- SESSION_INACTIVITY_TIMEOUT_SECONDS=900
- MYVD_CONFIG_PATH=WEB-INF/myvd.conf

`

Any advice would be appreciated. Thanks

**Comment by mlbiam** [comment]
@tkg61 So for some reason dockerhub (where the builds run automatically whenever we find updated packages) can't get to google's servers to download the kubectl packages.  Odd.  Until I can figure this out, i pushed the container built outside of dockerhub.  Can you try again?

**Comment by tkg61** [comment]
@mlbiam Thanks for the help! I was able to run it again and the process successfully completed. Now, i am working on getting to the main auth page since i don't see a port open on my k8 nodes for this container. I looked at the logs for the openunsion operator container and this kept repeating which looks different than the video tutorial:

`Is OpenShift : false
Loading Script : '/usr/local/openunison/js/deploy-objs.js'
Loading Script : '/usr/local/openunison/js/globals.js'
Loading Script : '/usr/local/openunison/js/deploy-upstream-k8s.js'
Loading Script : '/usr/local/openunison/js/helpers.js'
Loading Script : '/usr/local/openunison/js/deploy-openshift.js'
Loading Script : '/usr/local/openunison/js/operator.js'
/apis/openunison.tremolo.io/v1/namespaces/openunison/openunisons?watch=true&resourceVersion=5578538
Is OpenShift : false
Loading Script : '/usr/local/openunison/js/deploy-objs.js'
Loading Script : '/usr/local/openunison/js/globals.js'
Loading Script : '/usr/local/openunison/js/deploy-upstream-k8s.js'
Loading Script : '/usr/local/openunison/js/helpers.js'
Loading Script : '/usr/local/openunison/js/deploy-openshift.js'
Loading Script : '/usr/local/openunison/js/operator.js'
/apis/openunison.tremolo.io/v1/namespaces/openunison/openunisons?watch=true&resourceVersion=5578538
Is OpenShift : false
Loading Script : '/usr/local/openunison/js/deploy-objs.js'
Loading Script : '/usr/local/openunison/js/globals.js'
Loading Script : '/usr/local/openunison/js/deploy-upstream-k8s.js'
Loading Script : '/usr/local/openunison/js/helpers.js'
Loading Script : '/usr/local/openunison/js/deploy-openshift.js'
Loading Script : '/usr/local/openunison/js/operator.js'
/apis/openunison.tremolo.io/v1/namespaces/openunison/openunisons?watch=true&resourceVersion=5578538
`

Happy to open a new ticket for the above, just not sure if that is tied to this or not. 

Thanks!

**Comment by mlbiam** [comment]
Great! I'll keep this open until i get a root cause fix.  Yes, please open a new issue.  The output looks correct.

**Comment by mlbiam** [comment]
generation moved from dockerhub autobuilds to github actions
