### ISSUE TITLE
Deployment with istio gateway and virtualservice causes certificate issues

### ISSUE THREAD

**Issue by vbottu** [OpenUnison/openunison-k8s-login-activedirectory#75]
I have successfully deployed openunison using nginx ingress controller earlier but I want to leverage istio's ingress gateway with virtual services ,I was partially successful ,I got to the point where I can use my ldap credentials to login and after that both kubectl token and dashboard are not working. Below are the logs that I gathered while debugging.
 
Steps Followed:
1. Create openunison namespace and enable istio sidecar so that istio ingress gateway can be used
2. Deploy openunison operator
3. Create openunison source secret
4 . Deploy openunison orchestra by specifying openunison host and dashboard host(both are pointing to istio ingressgateway loadbalancer IP)
5. Get the tls certificate from ou-tls-certificate and add it all the kubernetes masters
6. Made sure the dashboard pod is killedand restarted and new certs are created
7. Create a gateway with https port 443 and use the ou-tls-certficate as credential so that proper certificate is used
8. Create virtualservice where both  the hosts(openunison and dashboard) points to openunison orchestra service
9. Use tls mode as PASSTHROUGH in istio so that the TLS is not terminated and sent as is.

Below are the errors that I am seeing in dashboard and openunison orchestra pods

**Dashboard logs:**
```
2020/06/18 21:50:22 http: TLS handshake error from *.*.*.*:****: remote error: tls: unknown certificate authority
2020/06/18 21:50:22 http: TLS handshake error from 1*.*.*.*:****: remote error: tls: unknown certificate authority
2020/06/18 21:50:23 http: TLS handshake error from 1*.*.*.*:****: remote error: tls: unknown certificate authority
2020/06/18 21:50:23 http: TLS handshake error from *.*.*.*:****: remote error: tls: unknown certificate authority
```

**Openunison orchestra logs:**
```
[2020-06-18 21:50:22,757][XNIO-1 task-5] INFO  AccessLog - [AuSuccess] - k8s - https://dashboardk8sdev.****.com/auth/oidc - uid=*****,ou=shadow,o=Tremolo - 20 / k8s-db-oidc [127.0.0.1] - [fc30cfff31b8ba9fb3c27047e440d79997b796432]
[2020-06-18 21:50:22,908][XNIO-1 task-10] INFO  AccessLog - [AzSuccess] - k8s - https://dashboardk8sdev.*****.com/ - uid=******,ou=shadow,o=Tremolo - oauth2bearer [127.0.0.1] - [fc30cfff31b8ba9fb3c27047e440d79997b796432]
[2020-06-18 21:50:22,985][XNIO-1 task-10] INFO  RetryExec - I/O exception (java.net.SocketException) caught when processing request to {s}->https://kubernetes-dashboard.kube-system.svc.cluster.local:443: Connection reset
[2020-06-18 21:50:22,985][XNIO-1 task-10] INFO  RetryExec - Retrying request to {s}->https://kubernetes-dashboard.kube-system.svc.cluster.local:443
[2020-06-18 21:50:22,995][XNIO-1 task-10] INFO  RetryExec - I/O exception (java.net.SocketException) caught when processing request to {s}->https://kubernetes-dashboard.kube-system.svc.cluster.local:443: Connection reset
[2020-06-18 21:50:22,996][XNIO-1 task-10] INFO  RetryExec - Retrying request to {s}->https://kubernetes-dashboard.kube-system.svc.cluster.local:443
[2020-06-18 21:50:23,114][XNIO-1 task-10] INFO  RetryExec - I/O exception (java.net.SocketException) caught when processing request to {s}->https://kubernetes-dashboard.kube-system.svc.cluster.local:443: Connection reset
[2020-06-18 21:50:23,114][XNIO-1 task-10] INFO  RetryExec - Retrying request to {s}->https://kubernetes-dashboard.kube-system.svc.cluster.local:443
[2020-06-18 21:50:23,190][XNIO-1 task-10] ERROR ProxySys - Error Executing Request :
[2020-06-18 21:50:23,191][XNIO-1 task-10] INFO  AccessLog - [Error] - k8s - https://dashboardk8sdev.*****.com/ - uid=******,ou=shadow,o=Tremolo - NONE [127.0.0.1] - [fc30cfff31b8ba9fb3c27047e440d79997b796432]
[2020-06-18 21:50:23,191][XNIO-1 task-10] ERROR ConfigSys - Could not process request
javax.servlet.ServletException: Could not execute request
        at com.tremolosecurity.proxy.ProxySys.doURI(ProxySys.java:112) ~[unison-server-core-1.0.18.jar:?]
        at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:141) ~[unison-server-core-1.0.18.jar:?]
        at com.tremolosecurity.proxy.auth.AuthMgrSys.doAuthMgr(AuthMgrSys.java:135) ~[unison-server-core-1.0.18.jar:?]
        at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:126) ~[unison-server-core-1.0.18.jar:?]
        at com.tremolosecurity.proxy.auth.AzSys.doAz(AzSys.java:139) ~[unison-sdk-1.0.18.jar:?]
        at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:111) ~[unison-server-core-1.0.18.jar:?]
        at com.tremolosecurity.proxy.auth.AuthSys.doAuth(AuthSys.java:162) ~[unison-server-core-1.0.18.jar:?]
        at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:105) ~[unison-server-core-1.0.18.jar:?]
        at com.tremolosecurity.proxy.ConfigSys.doConfig(ConfigSys.java:293) [unison-server-core-1.0.18.jar:?]
        at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:93) [unison-server-core-1.0.18.jar:?]
        at com.tremolosecurity.filter.UnisonServletFilter.doFilter(UnisonServletFilter.java:290) [unison-server-core-1.0.18.jar:?]
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-2.0.30.Final.jar:2.0.30.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-2.0.30.Final.jar:2.0.30.Final]
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) [undertow-servlet-2.0.30.Final.jar:2.0.30.Final]
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) [undertow-servlet-2.0.30.Final.jar:2.0.30.Final]
        at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) [undertow-servlet-2.0.30.Final.jar:2.0.30.Final]
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) [undertow-servlet-2.0.30.Final.jar:2.0.30.Final]
        at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) [undertow-servlet-2.0.30.Final.jar:2.0.30.Final]
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132) [undertow-servlet-2.0.30.Final.jar:2.0.30.Final]
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) [undertow-servlet-2.0.30.Final.jar:2.0.30.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.0.30.Final.jar:2.0.30.Final]
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) [undertow-core-2.0.30.Final.jar:2.0.30.Final]
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) [undertow-servlet-2.0.30.Final.jar:2.0.30.Final]
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) [undertow-core-2.0.30.Final.jar:2.0.30.Final]
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) [undertow-servlet-2.0.30.Final.jar:2.0.30.Final]
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) [undertow-core-2.0.30.Final.jar:2.0.30.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.0.30.Final.jar:2.0.30.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.0.30.Final.jar:2.0.30.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269) [undertow-servlet-2.0.30.Final.jar:2.0.30.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78) [undertow-servlet-2.0.30.Final.jar:2.0.30.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133) [undertow-servlet-2.0.30.Final.jar:2.0.30.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130) [undertow-servlet-2.0.30.Final.jar:2.0.30.Final]
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) [undertow-servlet-2.0.30.Final.jar:2.0.30.Final]
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) [undertow-servlet-2.0.30.Final.jar:2.0.30.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249) [undertow-servlet-2.0.30.Final.jar:2.0.30.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78) [undertow-servlet-2.0.30.Final.jar:2.0.30.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99) [undertow-servlet-2.0.30.Final.jar:2.0.30.Final]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376) [undertow-core-2.0.30.Final.jar:2.0.30.Final]
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830) [undertow-core-2.0.30.Final.jar:2.0.30.Final]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210) ~[?:1.8.0_252]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_252]
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465) ~[?:1.8.0_252]
        at sun.security.ssl.InputRecord.read(InputRecord.java:503) ~[?:1.8.0_252]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:990) ~[?:1.8.0_252]
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1388) ~[?:1.8.0_252]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1416) ~[?:1.8.0_252]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1400) ~[?:1.8.0_252]
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436) ~[httpclient-4.5.12.jar:4.5.12]
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384) ~[httpclient-4.5.12.jar:4.5.12]
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.12.jar:4.5.12]
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[httpclient-4.5.12.jar:4.5.12]
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.12.jar:4.5.12]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.12.jar:4.5.12]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.12.jar:4.5.12]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.12.jar:4.5.12]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.12.jar:4.5.12]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.12.jar:4.5.12]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.12.jar:4.5.12]
        at com.tremolosecurity.proxy.postProcess.UriRequestProcess.postProcess(UriRequestProcess.java:123) ~[unison-server-core-1.0.18.jar:?]
        at com.tremolosecurity.proxy.filter.HttpFilterChainImpl.nextFilter(HttpFilterChainImpl.java:92) ~[unison-server-core-1.0.18.jar:?]
        at com.tremolosecurity.proxy.ProxySys.doURI(ProxySys.java:97) ~[unison-server-core-1.0.18.jar:?]
        ... 41 more
```
I took the token generated and used with kubectl and got the below response
`Unable to connect to the server: Get https://logink8sdev.*****.com/auth/idp/k8sIdp/.well-known/openid-configuration: x509: certificate is valid for openunison.openunison.svc.cluster.local, not logink8sdev.*****.com`

**My Gateway:**
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: openunison-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - logink8sdev.******.com
    - dashboardk8sdev.*******.com
    tls:
      mode: PASSTHROUGH
      credentialName: ou-tls-certificate
```
**VirtualService:**
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: openunison-vs
  namespace: openunison
spec:
  hosts:
  - logink8sdev.*****.com
  - dashboardk8sdev.******.com
  gateways:
  - istio-system/openunison-gateway
  tls:
  - match:
    - port: 443
      sniHosts:
      - logink8sdev.*****.com
      - dashboardk8sdev.******.com
    route:
    - destination:
        host: openunison-orchestra
        port:
          number: 443
```
I removed the ingress that is created by openunison since it is not needed to access the service

Is there anything that I am missing here?

**Comment by vbottu** [comment]
And here is the certificate information
```
 Issuer: C=US, ST=State, L=My Cluster, O=MyOrg, OU=Kubernetes, CN=logink8sdev.******.com
        Validity
            Not Before: Jun 18 21:22:14 2020 GMT
            Not After : Jun 18 21:22:14 2021 GMT
        Subject: C=US, ST=State, L=My Cluster, O=MyOrg, OU=Kubernetes, CN=logink8sdev.*****.com
 X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:TRUE
            X509v3 Key Usage: critical
                Certificate Sign
            X509v3 Extended Key Usage: critical
                Any Extended Key Usage
            X509v3 Subject Alternative Name:
                DNS:logink8sdev.*******.com, DNS:dashboardk8sdev.*********.com

```

**Comment by mlbiam** [comment]
i think step #8 is the issue:

`Use tls mode as PASSTHROUGH in istio so that the TLS is not terminated and sent as is.`

With Itsio set with passthrough, does that make the pod the TLS endpoint or the virtual service?

**Comment by vbottu** [comment]
I am setting it to PASSTHROUGH by following this documentation https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/. It provides access to https service without terminating tls

**Comment by vbottu** [comment]
When I check the certificate in the browser it is issued to

**Comment by vbottu** [comment]
I kept on digging but could not figure out the issue. Wondering where this certificate is coming from . Actually the credential name is not required in gateway since we are using PASSTHROUGH so that the gateway sends the request to openunison via the route configured in virtualservice as is, it should work since the openunison has its own certificate . 

The issue is ,it is failing the verify the server certificate which is issued to openunison.openunison.svc.cluster.local

**Comment by vbottu** [comment]
Here is some debugging I did, I created a self signed certificate and key for a host nginx.example.com and deployed nginx server on kubernetes with istio side car and made a call to the nginx running on 443 using the below command from inside of the istio sidecar
`kubectl exec -it $(kubectl get pod  -n test-dev -l run=my-nginx -o jsonpath={.items..metadata.name}) -c istio-proxy -n test-dev -- curl -v -k --resolve nginx.example.com:443:127.0.0.1 https://nginx.example.com`

It works and I get a 200 code.

I tried the same with openunison and it gives connection refused. 
Why is the subject name openunison.openunison.svc.cluster.local instead of the hostnames?
Am I missing something here?

**Comment by mlbiam** [comment]
I believe its enabling passthrough is your issue.  Passthrough tells your ingress that you want to just pass the TCP/IP connection off to the pod, not the cert referenced by the ingress object or your virtual service.  The cert you are seeing with `openunison.openunison.svc.cluster.local` is the self signed cert we generate for traffic between the ingress and the pod.

**Comment by vbottu** [comment]
How do we tell the ingress to use ou-tls-certificate which is generated for Ou_host and dashboard_host. I tried setting it in the gateway it did not work. Can I try it with my own self signed certs? I see that openunison.openunison.svc.cluster.local is referred in openunison orchestra object , in case of my own certificates do I need to remove it as well?

**Comment by mlbiam** [comment]
what happens if you change `spec.tls.mode` from `PASSTHROUGH` to `SIMPLE`?  this should cause the ingress to reference the secret named in `spec.tls.credentialName` instead of the internal certificate

**Comment by vbottu** [comment]
It just gives 404. I guess using SIMPLE or MUTUAL tls mode terminates tls at the gateway itself.

**Comment by mlbiam** [comment]
is there a logentry in the openunison pod that says `NotFound`?

**Comment by vbottu** [comment]
Nope, the request is not going to openunison at all. Here is what I did
Created a gateway and specified the ou-tls-certificate as the tls credentials and created a virtual service that refers to the SNI hosts in the certificate which are ou and dashboard hosts.

**Comment by mlbiam** [comment]
let me see if i can get this running in my own testing cluster

**Comment by vbottu** [comment]
Sure. Thanks

**Comment by vbottu** [comment]
Is there a way we can get the ca-cert that signed the ou-tls-certificate entries?

**Comment by vbottu** [comment]
I tried multiple things and I am getting this error 
`[warning][config] [external/envoy/source/common/config/grpc_mux_subscription_impl.cc:82] gRPC config for type.googleapis.com/envoy.api.v2.Cluster rejected: Error adding/updating cluster(s) outbound|443||openunison-orchestra.openunison.svc.cluster.local: SAN-based verification of peer certificates without trusted CA is insecure and not allowed, outbound|80||openunison-orchestra.openunison.svc.cluster.local: SAN-based verification of peer certificates without trusted CA is insecure and not allowed`

**Comment by vbottu** [comment]
After some more debugging , I am facing a new issue now. below are the istio related objects I created
**Gateway**
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: openunison-gateway
  namespace: openunison
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: ou-tls-certificate
    hosts:
    - "openunison.example.com"
    - "dashboard.example.com"
```
**VirtualService:**

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: openunison-virtualservice
  namespace: openunison
spec:
  hosts:
  - "openunison.example.com"
  - "dashboard.example.com"
  gateways:
  - openunison-gateway
  http:
  - match:
    - uri:
        port: https
        prefix: /
    route:
    - destination:
        host: openunison-orchestra.openunison.svc.cluster.local
        port:
          number: 8443
```
**DestinationRule**
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: openunison-destinationrule
  namespace: openunison
spec:
  host: openunison-orchestra.openunison.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 8443 
      tls:
        mode: SIMPLE
```
**OutPut of Curl Command:**
curl -v -k https://openunison.example.com

```
* STATE: INIT => CONNECT handle 0x6df160; line 1392 (connection #-5000)
* Rebuilt URL to: https://openunison.example.com/
* Added connection 0. The cache now contains 1 members
* STATE: CONNECT => WAITRESOLVE handle 0x6df160; line 1428 (connection #0)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying *.*.*.*...
* TCP_NODELAY set
* STATE: WAITRESOLVE => WAITCONNECT handle 0x6df160; line 1509 (connection #0)
* Connected to openunison.example.com (*.*.*.*) port 443 (#0)
* STATE: WAITCONNECT => SENDPROTOCONNECT handle 0x6df160; line 1561 (connection #0)
* Marked for [keep alive]: HTTP default
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* STATE: SENDPROTOCONNECT => PROTOCONNECT handle 0x6df160; line 1575 (connection #0)
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0{ [5 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [96 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [1028 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=State; L=My Cluster; O=MyOrg; OU=Kubernetes; CN=openunison.example.com
*  start date: Jun 18 21:22:14 2020 GMT
*  expire date: Jun 18 21:22:14 2021 GMT
*  issuer: C=US; ST=State; L=My Cluster; O=MyOrg; OU=Kubernetes; CN=openunison.example.com
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
* STATE: PROTOCONNECT => DO handle 0x6df160; line 1596 (connection #0)
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* nghttp2_session_mem_recv() returns 0
} [5 bytes data]
* http2_send len=83
* h2 header: :method:GET
* h2 header: :path:/
* h2 header: :scheme:https
* h2 header: :authority:openunison.example.com
* h2 header: User-Agent:curl/7.58.0
* h2 header: Accept:*/*
* Using Stream ID: 1 (easy handle 0x6df160)
* before_frame_send() was called
} [5 bytes data]
* on_frame_send() was called, length = 35
> GET / HTTP/2
> Host: openunison.example.com
> User-Agent: curl/7.58.0
> Accept: */*
>
* STATE: DO => DO_DONE handle 0x6df160; line 1658 (connection #0)
* multi changed, check CONNECT_PEND queue!
* STATE: DO_DONE => WAITPERFORM handle 0x6df160; line 1783 (connection #0)
* STATE: WAITPERFORM => PERFORM handle 0x6df160; line 1799 (connection #0)
* http2_recv: easy 0x6df160 (stream 1)
{ [5 bytes data]
* nread=75
* Got SETTINGS
* MAX_CONCURRENT_STREAMS == 100
* ENABLE_PUSH == TRUE
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
* Got SETTINGS
* MAX_CONCURRENT_STREAMS == 100
* ENABLE_PUSH == TRUE
* on_begin_headers() was called
* h2 status: HTTP/2 503 (easy 0x6df160)
* h2 header: date: Thu, 25 Jun 2020 17:05:18 GMT
* on_frame_recv() header 1 stream 1
* Store 52 bytes headers from stream 1 at 0x6e9080
* on_stream_close(), NO_ERROR (err 0), stream 1
* Removed stream 1 hash!
* nghttp2_session_mem_recv() returns 75
* All data in connection buffer processed
} [5 bytes data]
* http2_recv: returns 52 for stream 1
* HTTP/2 found, allow multiplexing
< HTTP/2 503
< date: Thu, 25 Jun 2020 17:05:18 GMT
<
* http2_recv: easy 0x6df160 (stream 1)
* h2_process_pending_input: All data in connection buffer processed
* http2_recv returns 0, http2_handle_stream_close
{ [0 bytes data]
* http2_recv: easy 0x6df160 (stream 1)
* STATE: PERFORM => DONE handle 0x6df160; line 1968 (connection #0)
* multi changed, check CONNECT_PEND queue!
* multi_done
* free header_recvbuf!!
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to hostopenunison.example.com left intact

```
In Browser
`ERR_SSL_KEY_USAGE_INCOMPATIBLE`

**Comment by vbottu** [comment]
Hello @mlbiam , Any luck in testing with istio? I've tried several things but none of them seems to work, If I route toport 80in virtualservice then curl redirects it to 443 I believe and I am getting some response. It is not working from browser. I believe the application is terminating the connection. I see 200 status code in my sidecar and the request is terminated then by the openunison application.

**Comment by mlbiam** [comment]
@vbottu sorry it took me so long to sit down and get this working.  Here's how I got it working without the sidecar: https://github.com/TremoloSecurity/OpenUnison/wiki/troubleshooting#istio-ingress

**Comment by vbottu** [comment]
Thank you @mlbiam, I will try it out and get back to you

**Comment by vbottu** [comment]
It worked,thanks for the help

**Comment by vbottu** [comment]
Looks like the certificate is being rejected by chrome and edge, only works in firefox,in chrome and edge I am getting the below error
`ERR_SSL_KEY_USAGE_INCOMPATIBLE`
Is it something related to Key Usage in the config while generating certs?

**Comment by vbottu** [comment]
Sorry for the delay @mlbiam , here is the chrome version Version 84.0.4147.135 (Official Build) (64-bit) and I am on windows 10 64 bit.

**Comment by dkulchinsky** [comment]
Hey @mlbiam, having the same issue with Chrome Version 86.0.4240.111 on MacOS, works with Firefox. any ideas?

**Comment by mlbiam** [comment]
This is finally fixed if you're deploying a new orchestra.  If you have an existing orchestra you need to delete the `ou-tls-certificate` `Secret` in the `openunison` namespace.  Then either upgrade to the latest version of the helmchart or change `.spec.key_store.key_pairs.keys[1].ca_cert` from `true` to `false`.  The newly generated certificate in `ou-tls-certificate` will no longer be a CA certificate but will be recognized by both chrome AND the api server.
