### ISSUE TITLE
Upgrade from 1.0.18

### ISSUE THREAD

**Issue by vbottu** [OpenUnison/openunison-k8s-login-activedirectory#78]
Hi @mlbiam , I have setup openunison version 1.0.18 andeverything workedperfectly,I was able to customize the logos and other stuff as well. Now in the codebase i don't see the jsp's like the defaultForm.jsp etc. and if i try to use my custom built image with the latestversion of operator and this chart then orchestra pod fails with the below error.
```
java.security.KeyStoreException: Cannot overwrite own certificate
        at sun.security.pkcs12.PKCS12KeyStore.setCertEntry(PKCS12KeyStore.java:978)
        at sun.security.pkcs12.PKCS12KeyStore.engineSetCertificateEntry(PKCS12KeyStore.java:967)
        at java.security.KeyStore.setCertificateEntry(KeyStore.java:1201)
        at com.tremolosecurity.openunison.OpenUnisonConfigManager.loadKeystore(OpenUnisonConfigManager.java:296)
        at com.tremolosecurity.config.util.UnisonConfigManagerImpl.initialize(UnisonConfigManagerImpl.java:366)
        at com.tremolosecurity.filter.UnisonServletFilter.init(UnisonServletFilter.java:351)
        at com.tremolosecurity.openunison.OpenUnisonServletFilter.init(OpenUnisonServletFilter.java:118)
        at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:111)
        at io.undertow.servlet.core.ManagedFilter.createFilter(ManagedFilter.java:80)
        at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:591)
        at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:556)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:598)
        at com.tremolosecurity.openunison.undertow.OpenUnisonOnUndertow.main(OpenUnisonOnUndertow.java:329)
Exception in thread "main" javax.servlet.ServletException: java.security.KeyStoreException: Cannot overwrite own certificate
        at com.tremolosecurity.filter.UnisonServletFilter.init(UnisonServletFilter.java:382)
        at com.tremolosecurity.openunison.OpenUnisonServletFilter.init(OpenUnisonServletFilter.java:118)
        at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:111)
        at io.undertow.servlet.core.ManagedFilter.createFilter(ManagedFilter.java:80)
        at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:591)
        at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:556)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:598)
        at com.tremolosecurity.openunison.undertow.OpenUnisonOnUndertow.main(OpenUnisonOnUndertow.java:329)
Caused by: java.security.KeyStoreException: Cannot overwrite own certificate
        at sun.security.pkcs12.PKCS12KeyStore.setCertEntry(PKCS12KeyStore.java:978)
        at sun.security.pkcs12.PKCS12KeyStore.engineSetCertificateEntry(PKCS12KeyStore.java:967)
        at java.security.KeyStore.setCertificateEntry(KeyStore.java:1201)
        at com.tremolosecurity.openunison.OpenUnisonConfigManager.loadKeystore(OpenUnisonConfigManager.java:296)
        at com.tremolosecurity.config.util.UnisonConfigManagerImpl.initialize(UnisonConfigManagerImpl.java:366)
        at com.tremolosecurity.filter.UnisonServletFilter.init(UnisonServletFilter.java:351)
        ... 9 more
```
I dont see any jsp under webapp/auth/forms except cli-login-finished.jsp in the latest version. Appreciate your help

**Comment by mlbiam** [comment]
lets start with the JSPs.  There are no JSPs directly in the `openunison-k8s-login-activedirectory` project.  Their all inherited from the war from this section of `pom.xml`:

```
<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-war-plugin</artifactId>
        <version>2.6</version>
        <configuration>
          <overlays>
            <overlay>
              <groupId>com.tremolosecurity.unison</groupId>
              <artifactId>open-unison-webapp</artifactId>
            </overlay>
          </overlays>
        </configuration>
      </plugin>
```

so there won't be any JSPs in your own project except what you add and cli-login-finished.jsp.  What are you expecting to see that you don't?  When you run `mvn clean package` and look in `target/war/work/com.tremolosecurity.unison/open-unison-webapp/auth/forms ` you should see all the jsps:

```
ls target/war/work/com.tremolosecurity.unison/open-unison-webapp/auth/forms 
acknowledge.jsp              error.jsp                    jump.jsp                     pwdResetEmail.jsp            u2fAuth.jsp                
chooseLogin.jsp              firstRunError.jsp            loginTest.jsp                pwdResetNoUser.jsp           u2fRegistrationComplete.jsp
clearLogin.jsp               font/                        loginTestSimple.jsp          pwdResetSplash.jsp           u2fRegistration.jsp        
css/                         fonts/                       logout.jsp                   resetChain.jsp               userOnlyLogin.jsp          
defaultFailedLogin.jsp       images/                      noUser.jsp                   resetChooseLogin.jsp                                    
default-form.jsp             img/                         otp.jsp                      saml2_metadata.jsp                                      
defaultForm.jsp              js/                          postPreservation.jsp         secretQuestions.jsp                                     
duo/                         jumbotron-narrow.css         pwdResetBadKey.jsp           smsKey.jsp     
```

For the exception, that was fixed in 1.0.21 to make sure that the cacerts certificates were properly trusted.  In addition to upgrading to 1.0.21, you'll need to add `-Djavax.net.ssl.trustStore=/etc/openunison/unisonKeyStore.p12` to the `JAVA_OPTS` envionment variable defined in the `openunison-orchestra` `Deployment` in the `openunison` namespace.

**Comment by mlbiam** [comment]
sorry @vbottu i said 1.0.21 because thats the version we're working on now.  its 1.0.20 you want

**Comment by vbottu** [comment]
Thanks @mlbiam , I have tried customizing the webapp. But when I do a docker build all my changes are overridden from the overlay part. How do I customize the look and feel . In 1.0.18 i just changed the files under webapp and rebuilt the application and image and it worked.

Thanks.

**Comment by mlbiam** [comment]
it's the same process.  if you do `mvn clean package` are your custom jsps in `target/war/work/com.tremolosecurity.unison/open-unison-webapp/auth/forms` ?

**Comment by vbottu** [comment]
They are but they are getting replaced somehow by the default pages.

**Comment by mlbiam** [comment]
ok, can you verify the container you are running is the new one?  Both the `orchestra` `openunison` object and the `openunison-orchestra` `Deployment`?

**Comment by vbottu** [comment]
It is running the new containers for both openunison and orchestra.

**Comment by mlbiam** [comment]
if you exec into the openunison pod is your jsp there?

**Comment by vbottu** [comment]
When I place the modified jsps in auth/forms under webapp and do a clean package then in the target folder under war/work/com.tremolosecurity.unison/open-unison-webapp folder all the files does not have my changes. They are the default files and logos.

**Comment by mlbiam** [comment]
i'm sorry.  i pointed you at the wrong directory.  thats where maven pull files out from the original war.  are your customizations in `target/openunison-k8s-login-activedirectory-1.0.20/auth/forms/`?

**Comment by vbottu** [comment]
Yes, I can see my changes in that folder. But when the image is built and I deploy orchestra i somehow see the default pages and icons.

**Comment by mlbiam** [comment]
odd.  only thing i can think of is the image isn't being pulled.  do you have a specific tag you can use when building the new image?

**Comment by vbottu** [comment]
I am just using tag 1.0.20 for building the image

**Comment by mlbiam** [comment]
please try this:

1.  `mvn clean package`
2.  set your image to tag `1.0.20-fresh`
3.  `mvn compile jib:build`
4.  update the CR to point to `1.0.20-fresh`
5.  verify the `openunison-orchestra` `Deployment` is running `1.0.20-fresh`
6.  verify the `openunison-orchestra-aaaa` pods are running `1.0.20-fresh`
7.  remote shell into the `openunison-orchestra-aaaa` pod, check if your customizations are there
8.  In chrome, enable developer tools and check "disable cache"
9.  try logging in to openunison

**Comment by vbottu** [comment]
Sure, let me try that and get back.

**Comment by vbottu** [comment]
It worked. Thanks. However I am getting ERR_SSL_KEY_USAGE_INCOMPATIBLE in chrome(Version 85.0.4183.83 (Official Build) (64-bit)) and edge (Version 85.0.564.44 (Official build) (64-bit)) on windows 10 64 bit

**Comment by mlbiam** [comment]
great!  since we're tracking the cert issue in #75 i'll close this thread down
